config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'
  devise_for :users
  resources :questions, only: [:index, :new, :create] do
    resources :answers, only: [:new, :create] do
      resources :comments, except: [:index, :destroy]
    end
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  has_many :comments

  validates :body, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :answer
  belongs_to :user

  delegate :question, to: :answer

  validates :body, presence: true

  scope :confirmable, -> { where.not(confirmed_at: nil) }
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers

  validates :title, :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
  validates :email, format: { with: Devise.email_regexp }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_filter :authorize!
  before_action :set_question

  def new
    @answer = @question.answers.build
  end

  def create
    @answer = @question.answers.build(answer_params)

    if @answer.save
      respond_to do |format|
        format.html { redirect_to root_path, notice: 'Ответ успешно создан' }
        format.js
      end
    else
      render :new
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body).merge(user: current_user)
  end

  def set_question
    @question = Question.find(params[:question_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

  def authorize!
    unless signed_in?
      respond_to do |format|
        format.html { redirect_to new_user_session_path }
        format.js { render js: "window.location = '#{new_user_session_path}'" }
      end
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authorize!
  before_action :set_answer
  before_action :check_owner, only: [:edit, :update]

  def new
    @comment = @answer.comments.build
  end

  def create
    @comment = @answer.comments.build(comment_params)

    if @comment.save
      respond_to do |format|
        format.html { redirect_to root_path, notice: 'Правка успешно создана' }
        format.js
      end
    else
      render :new
    end
  end

  def edit
    @comment.body = "#{@comment.answer.body} #{@comment.body}"
  end

  def update
    @comment.touch(:confirmed_at)
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Правка успешно принята' }
      format.js
    end
  end

  private

  def set_answer
    @answer = Answer.find(params[:answer_id])
  end

  def check_owner
    if @answer && @answer.user != current_user
      redirect_to root_path, notice: 'Нет прав для этой операции'
    else
      @comment = Comment.find(params[:id])
    end
  end

  def comment_params
    params.require(:comment).permit(:body).merge(user: current_user)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authorize!, except: :index

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      respond_to do |format|
        format.html { redirect_to root_path, notice: 'Вопрос успешно добавлен' }
        format.js
      end
    else
      render :new
    end
  end

  private 

  def question_params
    params.require(:question).permit(:title, :body).merge(user: current_user)
  end
end

app/helpers/answers_helper.rb
# app/helpers/answers_helper.rb
module AnswersHelper
  def answer_body(answer)
    comments = answer.comments.confirmable.map do |x|
      content_tag(:span, x.body, class: "comment#{x.id}")
    end.join(' ')
    [answer.body, comments].join(' ').html_safe
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def navigation_links
    if current_user
      "#{current_user.name} #{link_to('Выход', destroy_user_session_path, method: :delete)}".html_safe
    else
      "#{link_to('Регистрация', new_user_registration_path)} / #{link_to('Вход', new_user_session_path)}".html_safe
    end
  end

  def content_title
    title = 'Вопросы'
    title += " - #{content_for(:title)}" if content_for?(:title)
    title
  end
end

app/helpers/comments_helper.rb
# app/helpers/comments_helper.rb
module CommentsHelper
  def confirm_icon(comment)
    comment.confirmed_at ? "\u{2713}" : "+"
  end

  def confirmed_at(comment)
    " #{content_tag(:span, 'принято', class: 'confirmed', data: { target: "comment#{comment.id}" })} #{time_ago_in_words(comment.confirmed_at)}".html_safe if comment.confirmed_at 
  end

  def confirm_comment_link(comment)
    link_to('Принять правку', edit_question_answer_comment_path(comment.question, comment.answer, comment), remote: true, id: "edit_comment_#{comment.id}") unless comment.confirmed_at
  end
end

app/helpers/devise_helper.rb
# app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" unless devise_error_messages?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg, class: 'alert alert-danger') }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <h4>#{sentence}</h4>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end

end

app/helpers/question_helper.rb
# app/helpers/question_helper.rb
module QuestionHelper
  def add_answer_link(question)
    name = question.answers.empty? ? 'Дать ответ' : 'Дать новый ответ'
    link_to(name, new_question_answer_path(question), remote: true, id: "add_answer_link_#{question.id}")
  end
end

app/views/answers/_answer.html.erb
<blockquote>
  <p><span id="answer_body_<%= answer.id %>"><%= answer_body(answer) %></span> - <strong><%= answer.user.name %></strong> <%= time_ago_in_words(answer.created_at) %></p>
  <div id="comment_block_<%= answer.id %>"><%= render partial: 'comments/comment', collection: answer.comments %></div>
  <p><%= link_to 'Предложить правку', new_question_answer_comment_path(answer.question, answer), remote: true, id: "add_comment_link_#{answer.id}" %></p>
</blockquote>

app/views/answers/_form.html.erb
<%= form_for([@question, @answer], remote: true, html: { id: "add_answer_form_#{@question.id}" }) do |f| %>
  <%= render 'shared/errors', object: @answer %>

  <div class="form-group">
    <%= f.label :body, class: 'control-label' %>
    <%= f.text_field :body, class: 'form-control', autofocus: true, placeholder: 'Дать ответ' %>
  </div>

  <div class="form-group">
    <%= f.submit 'Дать ответ', class: 'btn btn-info' %>
  </div>
<% end %>

app/views/answers/create.js.erb
$('#answer_block_<%= @question.id %>').append("<%=j render @answer %>");
$("#add_answer_link_<%= @question.id %>").show('slow', function() {
  $("#add_answer_form_<%= @question.id %>").remove();
});

app/views/answers/new.html.erb
<% content_for :title do %>
  Дать ответ
<% end %>

<h3>Дать ответ</h3>
<%= render 'form' %>

app/views/answers/new.js.erb
if ($("#add_answer_form_<%= @question.id %>").length == 0) {
  $("#add_answer_link_<%= @question.id %>").hide('slow', function() {
    $(this).after("<%=j render 'form' %>");
  });
} else {
  $("#add_answer_form_<%= @question.id %>").html("<%=j render 'form' %>");
}

app/views/comments/_comment.html.erb
<blockquote>
  <p><%= confirm_icon(comment) %> <%= comment.body %> - <strong><%= comment.user.name %></strong> <%= time_ago_in_words(comment.created_at) %><%= confirmed_at(comment) %></p>
  <%= confirm_comment_link(comment) %>
</blockquote>

app/views/comments/_form.html.erb
<%= form_for([@answer.question, @answer, @comment], remote: true, html: { id: "add_comment_form_#{@answer.id}" }) do |f| %>
  <%= render 'shared/errors', object: @comment %>

  <div class="form-group">
    <%= f.label :body, class: 'control-label' %>
    <%= f.text_field :body, class: 'form-control', autofocus: true, placeholder: 'Предложить правку' %>
  </div>

  <div class="form-group">
    <%= f.submit(@comment.new_record? ? "Предложить правку" : "Принять правку", class: 'btn btn-info') %>
  </div>
<% end %>

app/views/comments/create.js.erb
$('#comment_block_<%= @answer.id %>').append("<%=j render @comment %>");
$("#add_comment_link_<%= @answer.id %>").show('slow', function() {
  $("#add_comment_form_<%= @answer.id %>").remove();
})

app/views/comments/edit.html.erb
<% content_for :title do %>
  Принять правку
<% end %>

<h3>Принять правку</h3>
<%= render 'form' %>

app/views/comments/edit.js.erb
if ($("#add_comment_form_<%= @answer.id %>").length == 0) {
  $("#edit_comment_<%= @comment.id %>").hide('slow', function() {
    $(this).after("<%=j render 'form' %>");
  });
} else {
  $("#add_comment_form_<%= @answer.id %>").html("<%=j render 'form' %>");
}

app/views/comments/new.html.erb
<% content_for :title do %>
  Предложить правку
<% end %>

<h3>Предложить правку</h3>
<%= render 'form' %>

app/views/comments/new.js.erb
if ($("#add_comment_form_<%= @answer.id %>").length == 0) {
  $("#add_comment_link_<%= @answer.id %>").hide('slow', function() {
    $(this).after("<%=j render 'form' %>");
  });
} else {
  $("#add_comment_form_<%= @answer.id %>").html("<%=j render 'form' %>");
}

app/views/comments/update.js.erb
$("#answer_body_<%= @answer.id %>").html("<%=j answer_body(@answer) %>");
$('#comment_block_<%= @answer.id %>').html("<%=j render partial: 'comments/comment', collection: @answer.comments %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_title %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <% if alert %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= alert %>
  </div>
  <% end %>
  <% if notice %>
    <div class="alert alert-info">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= notice %>
    </div>
  <% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question, remote: true) do |f| %>
  <%= render 'shared/errors', object: @question %>

  <div class="form-group">
    <%= f.label :title, class: 'control-label' %>
    <%= f.text_field :title, autofocus: true, class: 'form-control', placeholder: 'Заголовок вопроса' %>
  </div>

  <div class="form-group">
    <%= f.label :body, class: 'control-label' %>
    <%= f.text_field :body, class: 'form-control', placeholder: 'Подробное описание ситуации' %>
  </div>

  <div class="form-group">
    <%= f.submit 'Задать вопрос', class: 'btn btn-info' %>
  </div>
<% end %>

app/views/questions/_question.html.erb
<blockquote>
  <p><strong><%= question.title %></strong> - <strong><%= question.user.name %></strong> <%= time_ago_in_words(question.created_at) %></p> 
  <p><%= question.body %></p>
  <div id="answer_block_<%= question.id %>"><%= render partial: 'answers/answer', collection: question.answers %></div>
  <p><%= add_answer_link(question) %></p>
</blockquote>

app/views/questions/create.js.erb
if ($('#empty_questions').length) {
  $('#empty_questions').remove();
}
$('#question_block').append("<%=j render @question %>");
$('#new_question_link').show('slow', function() {
  $('#new_question').remove();
});

app/views/questions/index.html.erb
<div class="text-center">
  <h1>Вопросы</h1>
  <h3><%= navigation_links %></h3>
</div>
<div id="question_block">
  <% if @questions.empty? %>
    <div id="empty_questions">Вопросов пока нет</div>
  <% else %>
    <%= render partial: 'question', collection: @questions %>
  <% end %>
</div>
<%= link_to 'Задать вопрос', new_question_path, remote: true, id: 'new_question_link' %>

app/views/questions/new.html.erb
<% content_for :title do %>
  Задать вопрос
<% end %>

<h3>Задать вопрос</h3>
<%= render 'form' %>

app/views/questions/new.js.erb
if ($('#new_question').length == 0) {
  $('#new_question_link').hide('slow', function() {
    $(this).after("<%=j render 'form' %>");
  });
} else {
  $('#new_question').html("<%=j render 'form' %>");
}

app/views/shared/_errors.html.erb
<% if object.errors.full_messages.present? %>
  <div class="alert alert-danger" role="error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>